const $=s=>document.querySelector(s), $$=s=>document.querySelectorAll(s);
let me=null, state={members:[],applications:[],ideas:[],tasks:[],announcements:[],events:[],audit:[]}, current='dashboard';
const nav={member:[['▦','Dashboard','dashboard'],['◉','My Profile','profile'],['◈','My Projects','projects'],['⌁','Research Workspace','research'],['✓','My Tasks','tasks'],['◷','Events','events'],['↗','Opportunities','opportunities'],['☆','Certificates','certificates'],['♧','Announcements','announcements'],['⚙','Settings','settings']],lead:[['▦','Dashboard','dashboard'],['◈','My Projects','projects'],['⌁','Research Workspace','research'],['✓','Team Tasks','tasks'],['♧','Team Collaboration','collaboration'],['◷','Events','events'],['⚙','Settings','settings']],mentor:[['▦','Research Dashboard','dashboard'],['◈','Assigned Projects','projects'],['⌁','Research Pipeline','research'],['✓','Review Requests','reviews'],['♧','Feedback History','feedback'],['◷','Meetings','events'],['⚙','Settings','settings']],admin:[['▦','Dashboard','dashboard'],['◷','Applications','applications'],['◉','Member Management','members'],['♧','Roles & Teams','teams'],['◈','Projects','projects'],['⌁','Research Management','research'],['◷','Events','events'],['↗','Opportunities','opportunities'],['☆','Certificates','certificates'],['♧','Announcements','announcements'],['▤','Reports','reports'],['⚙','Settings','settings'],['◷','Audit Logs','audit']],superadmin:[['▦','Dashboard','dashboard'],['◷','Applications','applications'],['◉','Member Management','members'],['♧','Roles & Teams','teams'],['◈','Projects','projects'],['⌁','Research Management','research'],['◷','Events','events'],['↗','Opportunities','opportunities'],['☆','Certificates','certificates'],['♧','Announcements','announcements'],['▤','Reports','reports'],['▣','Private Support Records','support'],['⚙','Settings','settings'],['◷','Audit Logs','audit']]};
async function api(url,opt={}){const r=await fetch(url,{credentials:'same-origin',...opt});let j={};try{j=await r.json()}catch{}if(!r.ok)throw new Error(j.detail||j.message||'Request failed');return j}
async function refresh(){const j=await api('/api/state');me=j.user;state=j;}
function status(s){let c=/pending|review|submitted|wait/i.test(s)?'warn':/reject|overdue|disabled/i.test(s)?'danger':/draft|to do/i.test(s)?'gray':'';return `<span class="status ${c}">${s}</span>`}
function table(h,rows){return `<div class="table-wrap"><table class="data-table"><thead><tr>${h.map(x=>`<th>${x}</th>`).join('')}</tr></thead><tbody>${rows.map(r=>`<tr>${r.map(x=>`<td>${x}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`}
function metric(n,l,i){return `<article class="metric"><i>${i}</i><strong>${n}</strong><span>${l}</span></article>`}
function dashboard(){let admin=['admin','superadmin'].includes(me.role);return `<section class="welcome"><div><h2>${admin?'Club at a glance.':`Welcome, ${me.name}.`}</h2><p>Your RISE workspace is connected to the secure server.</p></div><span class="chip">● Secure session active</span></section><section class="metric-grid">${admin?metric(state.members.length,'Members','◉')+metric(state.applications.filter(x=>x.status==='Pending').length,'Pending applications','◷')+metric(state.tasks.length,'Tasks','✓')+metric(state.ideas.length,'Research ideas','⌁'):metric(state.tasks.filter(x=>x.status!=='Completed').length,'Open tasks','✓')+metric(state.ideas.length,'Research ideas','⌁')+metric(state.events.length,'Events','◷')+metric(state.announcements.length,'Announcements','♧')}</section><section class="panel-grid"><article class="panel"><h3>Recent announcements</h3>${state.announcements.slice(0,4).map(x=>`<div class="mini-list"><li><i class="dot"></i><div><b>${x.title}</b><small>${x.audience} · ${new Date(x.published_at).toLocaleDateString()}</small></div></li></div>`).join('')}</article><article class="panel"><h3>Quick actions</h3><div class="actions-row"><button class="button quick" data-page="research">Submit research idea</button><button class="button button-ghost quick" data-page="tasks">View tasks</button></div></article></section>`}
function research(){return `<section class="welcome"><div><h2>Research workspace</h2><p>Submit ideas to the central RISE database.</p></div><button class="button modal-action" data-form="idea">+ Submit idea</button></section><section class="panel"><h3>Research idea bank</h3>${table(['Idea','Domain','Status','Owner'],state.ideas.map(x=>[x.title,x.domain,status(x.status),x.owner]))}</section>`}
function tasks(){return `<section class="welcome"><div><h2>Tasks</h2><p>Tasks are stored centrally and linked to your account.</p></div>${['admin','superadmin','lead'].includes(me.role)?'<button class="button modal-action" data-form="task">+ Add task</button>':''}</section>${state.tasks.map(x=>`<article class="task-card"><div><span class="priority">${x.priority.toUpperCase()} PRIORITY</span><h4>${x.title}</h4><p>${x.project} · Due ${x.deadline||'—'}</p></div><div>${status(x.status)} ${x.status!=='Completed'&&(['member','lead'].includes(me.role))?`<button class="table-btn complete-task" data-id="${x.id}">Mark complete</button>`:''}</div></article>`).join('')||'<div class="empty">No tasks yet.</div>'}`}
function members(){return `<section class="welcome"><div><h2>Member management</h2><p>Only administrators can create, disable, or restore member accounts.</p></div><button class="button modal-action" data-form="member">+ Create member</button></section>${table(['Member','Department','Role','Status','Action'],state.members.map(x=>[`${x.name}<br><small>${x.email}</small>`,x.department,x.role,status(x.status),`<button class="table-btn member-status" data-id="${x.id}" data-status="${x.status==='active'?'disabled':'active'}">${x.status==='active'?'Disable':'Enable'}</button>`]))}`}
function applications(){return `<section class="welcome"><div><h2>Applications</h2><p>Review applications submitted through the public RISE website.</p></div></section>${table(['Applicant','Email','Domain','Status'],state.applications.map(x=>[x.name,x.email,x.domain,status(x.status)]))}`}
function announcements(){return `<section class="welcome"><div><h2>Announcements</h2><p>Centralized announcements visible to signed-in members.</p></div>${['admin','superadmin'].includes(me.role)?'<button class="button modal-action" data-form="announcement">+ New announcement</button>':''}</section>${table(['Announcement','Priority','Audience','Published'],state.announcements.map(x=>[x.title,status(x.priority),x.audience,new Date(x.published_at).toLocaleString()]))}`}
function events(){return `<section class="welcome"><div><h2>Events</h2><p>Events are stored centrally for the whole club.</p></div>${['admin','superadmin','lead'].includes(me.role)?'<button class="button modal-action" data-form="event">+ Create event</button>':''}</section>${table(['Event','Date & time','Venue','Limit'],state.events.map(x=>[x.title,x.date_time,x.venue,x.limit_count||'—']))}`}
function reports(){return `<section class="welcome"><div><h2>Reports</h2><p>Download current server data as CSV.</p></div></section><section class="panel"><div class="opportunity-grid">${['members','applications','tasks','audit'].map(x=>`<article class="opportunity"><span class="tag">CSV</span><h3>${x[0].toUpperCase()+x.slice(1)}</h3><p>Export current ${x} data.</p><button class="text-link" onclick="location.href='/api/reports/${x}.csv'">Download CSV →</button></article>`).join('')}</div></section>`}
function audit(){return `<section class="welcome"><div><h2>Audit logs</h2><p>Server-recorded operational activity.</p></div></section>${table(['Timestamp','Actor','Action'],state.audit.map(x=>[new Date(x.timestamp).toLocaleString(),x.actor,x.action]))}`}
function profile(){return `<section class="welcome"><div><h2>My profile</h2><p>Your account identity is managed by RISE administration.</p></div></section><section class="panel"><h3>${me.name}</h3><p>${me.email}</p><p>${me.department||'Department not set'} · ${me.role}</p><p>Account status: ${status(me.status)}</p></section>`}
function simple(t,s){return `<section class="welcome"><div><h2>${t}</h2><p>${s}</p></div></section><div class="empty">This module is protected by the same server-side authentication system.</div>`}
const views={dashboard,research,tasks,members,applications,announcements,events,reports,audit,profile,projects:()=>simple('Projects','Project records can be connected to the same database.'),opportunities:()=>simple('Opportunities','Club opportunities are ready for server-backed records.'),certificates:()=>simple('Certificates','Certificate records can be issued and stored centrally.'),teams:()=>simple('Roles & teams','Team assignments are managed by administrators.'),support:()=>simple('Private support records','Restricted to authorised administrators.'),collaboration:()=>simple('Team collaboration','Shared collaboration is protected by account roles.'),reviews:()=>simple('Review requests','Mentor review queue.'),feedback:()=>simple('Feedback history','Mentor feedback history.'),settings:()=>simple('Settings','Account and notification settings.')};
function render(){const ns=nav[me.role]||nav.member;$('#userName').textContent=me.name;$('#userRole').textContent=me.role;$('#userInitials').textContent=me.name.split(' ').map(x=>x[0]).join('').slice(0,2);$('#sideNav').innerHTML=ns.map(n=>`<button class="${current===n[2]?'active':''}" data-page="${n[2]}"><span class="nav-ico">${n[0]}</span>${n[1]}</button>`).join('');$('#pageTitle').textContent=ns.find(n=>n[2]===current)?.[1]||'Dashboard';$('#notificationCount').textContent=state.announcements.length;$('#pageContent').innerHTML=(views[current]||dashboard)();$$('[data-page]').forEach(x=>x.onclick=()=>{current=x.dataset.page;render()});$$('.modal-action').forEach(x=>x.onclick=()=>openForm(x.dataset.form));$$('.complete-task').forEach(x=>x.onclick=async()=>{await api('/api/tasks/'+x.dataset.id,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({status:'Completed'})});await refresh();render()});$$('.member-status').forEach(x=>x.onclick=async()=>{await api('/api/members/'+x.dataset.id,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({status:x.dataset.status})});await refresh();render()});$('.sidebar-toggle').onclick=()=>$('.sidebar').classList.toggle('open');}
function openForm(type){let fields={member:[['name','Full name'],['email','University email'],['department','Department / year'],['role','Role (member/lead/mentor)']],idea:[['title','Idea title'],['domain','Research domain'],['statement','Problem statement'],['impact','Expected impact']],task:[['title','Task title'],['project','Project'],['priority','Priority'],['deadline','Deadline'],['assigned_to','Assigned member ID (optional)']],announcement:[['title','Announcement title'],['priority','Priority'],['audience','Target audience'],['message','Message']],event:[['title','Event title'],['date_time','Date & time'],['venue','Venue'],['limit_count','Registration limit']]}[type];$('#appModalContent').innerHTML=`<form class="app-modal-form" id="entryForm"><h2>Create ${type}</h2><div class="form-grid">${fields.map(([n,l],i)=>`<label class="${i===2?'wide':''}">${l}${/statement|impact|message/i.test(n)?'<textarea name="'+n+'" required></textarea>':'<input name="'+n+'" '+(n==='email'?'type="email"':'')+' required>'}</label>`).join('')}</div><button class="button" type="submit">Save →</button></form>`;$('#appModal').showModal();$('#entryForm').onsubmit=async e=>{e.preventDefault();const d=Object.fromEntries(new FormData(e.target));if(d.assigned_to)d.assigned_to=Number(d.assigned_to);if(d.limit_count)d.limit_count=Number(d.limit_count);let endpoint={member:'/api/members',idea:'/api/ideas',task:'/api/tasks',announcement:'/api/announcements',event:'/api/events'}[type];try{const j=await api(endpoint,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(d)});$('#appModal').close();await refresh();render();if(j.message)alert(j.message)}catch(err){alert(err.message)}}}
$('#loginForm').onsubmit=async e=>{e.preventDefault();$('#loginHelp').textContent='Signing in…';try{const j=await api('/api/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email:$('#email').value,password:$('#password').value})});me=j.user;await refresh();$('#login').hidden=true;$('#app').hidden=false;current='dashboard';render()}catch(err){$('#loginHelp').textContent=err.message}};
$('#logout').onclick=async()=>{await api('/api/logout',{method:'POST'});location.reload()};$('.modal-close').onclick=()=>$('#appModal').close();$('#showNotifications').onclick=()=>{current='announcements';render()};
(async()=>{try{await refresh();$('#login').hidden=true;$('#app').hidden=false;render()}catch{}})();
